# Sample workflow for building and deploying an org-static-blog site to GitHub Pages
#
# To get started with org-static-blog see: https://github.com/bastibe/org-static-blog
#
name: Deploy org-static-blog site to Pages

on:
  # Runs on pushes targeting the default branch
  [push]
  # push:
  #   branches: [$default-branch]

  # Allows you to run this workflow manually from the Actions tab

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: 28.2
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get org-static-blog
        id: get-org-static-blog
        run: |
          wget -O ${{ runner.temp }}/org-static-blog.el  https://raw.githubusercontent.com/bastibe/org-static-blog/refs/heads/master/org-static-blog.el\
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build blog
        run: |
          if [ -f CNAME ]; then
            DOMAIN_NAME=$(cat CNAME)
          else
            DOMAIN_NAME="${{ github.repository_owner }}.github.io"
          fi &&
          emacs -Q --script build.el ${{ runner.temp }}/org-static-blog.el $DOMAIN_NAME &&
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
